-- Deprecated shim kept for reference.
-- Simple unified member system has been replaced by database/members_setup.sql.
-- This file intentionally contains no executable SQL to avoid conflicting schemas.
