-- LEGACY SCHEMA NOTE
-- This file previously contained the legacy member schema and has been moved to
-- `database/legacy/memberDataSchema.sql` to avoid accidental runtime references.
-- Keep the migration artifact in the `database/legacy/` folder. Runtime code should
-- use the normalized live model: members, member_monthly_balances, member_dues, org_balance_history
-- and the RPCs: api_get_dashboard / api_get_member_timeline.